### ISSUE TITLE
Plugin works not with Grav v1.1.1 - Admin v1.1.2

### ISSUE THREAD

**Issue by larsroettig** [kwachu96/grav-plugin-cookies-notice#1]
Hi, 
i installed  the Plugin it works not with the last build and will not visible at the backend. 

best regards lars

**Comment by kwachu96** [comment]
Hello, 
Thanks for reporting, I check files and I saw problem in blueprints.yaml file. version 1.0.2 should work with installation by gpm / admin, because value of field `name` contain space between words.
Regards, kwachu

**Comment by kwachu96** [comment]
It has been repaired work. Thank you for notification.
