### ISSUE TITLE
Customise Text

### ISSUE THREAD

**Issue by kamaleshdubey** [kwachu96/grav-plugin-cookies-notice#6]
How do I customise the text of the notice? I cannot see any way of doing this from the Admin console. Is there a file that I can edit in the back-end?

**Comment by kwachu96** [comment]
You can edit text of notice in this file https://github.com/kwachu96/grav-plugin-cookies-notice/blob/master/languages.yaml

**Comment by kamaleshdubey** [comment]
Thanks mate.
