### ISSUE TITLE
isn't working

### ISSUE THREAD

**Issue by RUSampson** [kwachu96/grav-plugin-cookies-notice#7]
Hello
I've some troubles) How can i help you more?
grav newest release + gantry5 + skeleton.
But also check plugin with clear installation (grav only) few days ago - before release 113 - the same errors

<script>
    $(document).ready(function() {
         $.showCookiesNotice("{{ 'PLUGINS.COOKIES_NOTICE.COOKIE'|t }}", "{{ cookiesnotice_url }}", "{{ 'PLUGINS.COOKIES_NOTICE.LINK'|t }}", "{{ 'PLUGINS.COOKIES_NOTICE.DIMISS'|t }}", "{{ cookiesnotice_position }}");
     });
</script>
 
Arguments
"An exception has been thrown during the rendering of a template ("Failed to read languages.yaml: Malformed inline YAML string: 'Cerrar at line 60 (near "DIMISS: 'Cerrar").")."
Environment & details:

**Comment by kwachu96** [comment]
Hello, Thank you for your report. Now it should work with last release.
